[build]
  base = "gta-boat-charter"
  command = "npm run build"
  publish = ".netlify"

[functions]
  directory = "gta-boat-charter/netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
